ISpan.InseparableCore/Controllers/ShoppingController.cs
using ISpan.InseparableCore.Models.BLL;
using ISpan.InseparableCore.Models.BLL.Interfaces;
using ISpan.InseparableCore.Models.DAL;
using ISpan.InseparableCore.Models.DAL.Repo;
using ISpan.InseparableCore.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using ISpan.InseparableCore.Models;
using System.Collections.Generic;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Mail;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Web;

namespace ISpan.InseparableCore.Controllers
{
    public class ShoppingController :  SuperController
    {
        private readonly InseparableContext _db;
        private readonly ApiKeys _key;
        private readonly OrderRepository _order_repo;
        private readonly TicketOrderRepository _ticket_repo;
        private readonly ProductOrderRepository _product_order_repo;
        private readonly SessionRepository _session_repo;
        private readonly CinemaRepository _cinema_repo;
        private readonly ProductRepository _product_repo;
        private readonly SeatRepository _seat_repo;
        private readonly MovieRepository _movie_repo;
        public ShoppingController(InseparableContext db,IOptions<ApiKeys> key)
        {
            _db = db;
            _key = key.Value;
            _order_repo = new OrderRepository(db);
            _ticket_repo = new TicketOrderRepository(db);
            _product_order_repo = new ProductOrderRepository(db);
            _session_repo = new SessionRepository(db);
            _cinema_repo = new CinemaRepository(db);
            _product_repo = new ProductRepository(db);
            _seat_repo = new SeatRepository(db);
            _movie_repo = new MovieRepository(db, null);
        }

       //選擇影院電影
        public IActionResult Ticket(CticketVM vm)
        {
            //以防萬一只要一開啟訂購畫面 第一件事清空訂單session
            HttpContext.Session.Remove(CDictionary.SK_PURCHASED_PRODUCTS_LIST);
            HttpContext.Session.Remove(CDictionary.SK_PURCHASED_TICKET_LIST);

            vm.cinema = _cinema_repo.QueryAll();
            if(vm.cinema==null)
                return RedirectToAction("Index", "Home");

            vm.cinemaId = vm.cinemaId == null ? 0 : vm.cinemaId;

            //時間區間一周
            var now = DateTime.Now.TimeOfDay;
            var start = DateTime.Now.Date;

            //第一次傳回cinemaId
            if (vm.cinemaId != 0)
            {
                vm.movie = _session_repo.GetMovieByCinema(vm.cinemaId);
                if (vm.movie.Count()==0)
                    return View(vm);
                vm.movieId = vm.movieId == null ? 0 : vm.movieId;
            }
            //第二次傳回movieId
            if (vm.movieId > 0)
            {
                var date = _session_repo.GetSessionByTwoCondition(vm.cinemaId,vm.movieId).OrderBy(t=>t.FSessionDate).GroupBy(t => t.FSessionDate).Select(t => t.Key);
                if (date.Count() == 0)
                    return View(vm);

                //分日期跟場次 用Dictionary來接資料
                vm.sessions = new Dictionary<DateTime, IEnumerable<TSessions>>();
                foreach (var item in date)
                {
                    IEnumerable<TSessions> sessions = null;

                    sessions = _session_repo.GetSessionByTwoCondition(vm.cinemaId, vm.movieId).Where(t => t.FSessionDate == item).OrderBy(t=>t.FSessionTime);
                    if (item==start)
                        sessions = _session_repo.GetSessionByTwoCondition(vm.cinemaId, vm.movieId).Where(t => t.FSessionDate == item && t.FSessionTime>now).OrderBy(t => t.FSessionTime);

                    if(sessions.Count()!=0)
                        vm.sessions.Add(item, sessions);
                }
            }
            return View(vm);
        }
        //選擇商品(餐點 票券)
        public IActionResult Booking(int? cinema, int? session)
        {
            CbookingVM vm = new CbookingVM();
            if (session == null ||cinema==null)
            {
                return RedirectToAction("Ticket");
            }
            vm.sessions = _session_repo.GetSessionBySession(session);
            vm.movie = _session_repo.GetMovieBySEssion(session);
            vm.cinema = _session_repo.GetCinemaBySEssion(session);
            vm.products = _product_repo.GetProductByCinema(cinema);

            return View(vm);
        }

        //Ajax紀錄商品資訊在session
        public IActionResult ProductItem(int? productId, int? quantity)
        {
            string responseText = "fail";

            if (productId == null)
                return Ok(responseText);
            var product = _product_repo.GetOneProduct(productId);

            if (product == null)
                return BadRequest("糟糕...出錯了");

            List<CproductCartItem> cart = null;
            string json = string.Empty;
            if (HttpContext.Session.Keys.Contains(CDictionary.SK_PURCHASED_PRODUCTS_LIST))
            {
                json = HttpContext.Session.GetString(CDictionary.SK_PURCHASED_PRODUCTS_LIST);
                cart = JsonSerializer.Deserialize<List<CproductCartItem>>(json);
            }
            else
                cart = new List<CproductCartItem>();

            //同一商品只記錄一次 避免同一商品出現兩次
            CproductCartItem delete = null;
            foreach (var p in cart)
            {
                if (p.FProductId == productId)
                {
                    delete = cart.FirstOrDefault(c => c.FProductId == p.FProductId);
                }
            }
            cart.Remove(delete);

            //確認是否有數量 如果沒有就不能存在session裡
            if (quantity > 0)
            {
                CproductCartItem item = new CproductCartItem();
                item.FProductItemNo = cart.Count() > 0 ? cart.Count() + 1 : 1;
                item.FProductUnitprice = product.FProductUnitprice;
                item.FProductQty = (int)quantity;
                item.FProductId = (int)productId;
                item.FProductName = product.FProductName;

                cart.Add(item);
            }
            json = JsonSerializer.Serialize(cart);
            HttpContext.Session.SetString(CDictionary.SK_PURCHASED_PRODUCTS_LIST, json);
            if (cart.Count() > 0)
                responseText = "pass";
            if (quantity == 0)
                responseText = "fail";
            return Ok(responseText);
        }

        //選擇座位
        public IActionResult Seat(CseatVM vm)
        {
            if (vm == null || vm.sessionid == null)
            {
                string error = "網頁加載時出現問題";
                return RedirectToAction("Error", new { error });
            }

            //紀錄已賣出的座位Id
            vm.solid = new List<int>();
            var solid = _ticket_repo.GetSolid(vm.sessionid ,true);

            foreach (var item in solid)
            {
                vm.solid.Add(item.FSeatId);
            }

            //座位按排紀錄到Dictionary
            vm.seats = new Dictionary<string, IEnumerable<TSeats>>();
            var row = _seat_repo.GetSeat().GroupBy(t => t.FSeatRow).Select(t => t.Key);
            if( row.Count()==0)
            {
                string error = "網頁加載時出現問題";
                return RedirectToAction("Error", new { error });
            }
            foreach (var item in row)
            {
                var column = _seat_repo.GetSeat().Where(t => t.FSeatRow == item);
                if(column.Count()!=0)
                    vm.seats.Add(item, column);
            }

            vm.sessions = _session_repo.GetOneSession(vm.sessionid);
            vm.movie = _session_repo.GetMovieBySEssion(vm.sessionid);
            return View(vm);
        }

        //Ajax將票券記錄在session
        public IActionResult TicketItem(int? seatId, int? Qty, int? sessionId)
        {
            string responseText = "fail";

            if (seatId == null || sessionId == null)
                return Ok(responseText);

            var session = _session_repo.GetOneSession(sessionId);
            if(session ==null)
            {
                return BadRequest("糟糕...出錯啦");
            }
            List<CticketCartItemVM> cart = null;
            string json = string.Empty;
            if (HttpContext.Session.Keys.Contains(CDictionary.SK_PURCHASED_TICKET_LIST))
            {
                json = HttpContext.Session.GetString(CDictionary.SK_PURCHASED_TICKET_LIST);
                cart = JsonSerializer.Deserialize<List<CticketCartItemVM>>(json);
            }
            else
                cart = new List<CticketCartItemVM>();

            //位置取消session也要刪除
            CticketCartItemVM delete = null;
            if (Qty == 0)
            {
                delete = cart.FirstOrDefault(c => c.FSeatId == seatId);
                cart.Remove(delete);
            }
            else
            {
                CticketCartItemVM item = new CticketCartItemVM();
                item.FTicketUnitprice = (decimal)session.FTicketPrice;
                item.FTicketItemNo = cart.Count() > 0 ? cart.Count() + 1 : 1;
                item.FMovieId = session.FMovieId;
                item.FMovieName = _movie_repo.GetOneMovie(session.FMovieId).FMovieName;
                item.FRoomId = session.FRoomId;
                item.FSeatId = (int)seatId;
                item.FSessionId = (int)sessionId;

                cart.Add(item);
            }

            json = JsonSerializer.Serialize(cart);
            HttpContext.Session.SetString(CDictionary.SK_PURCHASED_TICKET_LIST, json);
            responseText = "pass";
            return Ok(responseText);
        }
        //購物車預覽
        public IActionResult CartView(int? regular, int? concession, int? sessionid)
        {
            if (regular == null || concession == null || sessionid == null)
            {
                string error = "網頁加載時出現問題";
                return RedirectToAction("Error", new { error });

ISpan.InseparableCore/Views/Shopping/Booking.cshtml
@model ISpan.InseparableCore.ViewModels.CbookingVM

@{
    ViewData["Title"] = "Booking";
}
@section Styles{
    <link href="~/css/blog.css" rel="stylesheet">
    <link href="~/css/Booking.css" rel="stylesheet">
}
    <form action="/Shopping/Seat" method="post">
    @if (Model.movie.Count()!=0)
    {
        foreach (var item in Model.movie)
        {
            <h1>@item.FMovieName</h1>
        }
    }
    <section id="blog" class="pt-4 pb-4 bg_grey">
        <div class="row blog_1">
            <div class="col-md-8">
                <div class="blog_1l1">
                    @if (Model.sessions != null)
                    {
                        foreach (var item in Model.sessions)
                        {
                            <input type="hidden" name="sessionid" value="@item.FSessionId" />

                            <h4><img src="https://img.icons8.com/ultraviolet/40/null/overtime.png" /> @item.FSessionDate.ToString("yyyy/MM/dd")  @item.FSessionTime.Hours : @item.FSessionTime.Minutes.ToString("D2")</h4>

                            <div>
                                <h4 class="background">選擇電影票</h4>
                                <table>
                                    <thead>
                                        <tr>
                                            <th>票種</th>
                                            <th>價格</th>
                                            <th>張數</th>
                                            <th>合計</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td id="regular">全票</td>
                                            <td id="regularprice">@Convert.ToInt32(item.FTicketPrice)</td>
                                            <td>
                                                <select id="regularnum" name="regularnum" onchange="cal();caritem()">
                                                    @for (int i = 0; i < 11; i++)
                                                    {
                                                        <option value="@i">@i</option>
                                                    }
                                                </select>
                                            </td>
                                            <td id="regularsubtotal">0</td>
                                        </tr>
                                        <tr>
                                            <td id="concession">優待票</td>
                                            <td id="concessionprice"></td>
                                            <td>
                                                <select id="concessionnum" name="concessionnum" onchange="cal();caritem()">
                                                    @for (int i = 0; i < 11; i++)
                                                    {
                                                        <option value="@i">@i</option>
                                                    }
                                                </select>
                                            </td>
                                            <td id="concessionsubtotal">0</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        }
                    }
                    <div>
                        <h4 class="background">選擇商品</h4>
                        @if(Model.products!=null){
                            int count = 0;
                            foreach (var item in Model.products)
                            {
                                count++;
                                <span>
                                    <h3>@item.FProductName</h3>

                                    <img src="~/images/@item.FProductPicturePath" width="150" height="150" />
                                    <div class="margin-top">
                                        <p>@item.FProductUnitprice.ToString("###") 元</p>
                                        <select name="@item.FProductName" id="product" price="@item.FProductUnitprice" pid="@item.FProductId" onchange="record(this);caritem()">
                                            @for (int i = 0; i < 11; i++)
                                            {
                                                <option value="@i">@i</option>
                                            }
                                        </select>
                                    </div>

                                </span>
                            }
                        }
                    </div>

                </div>
            </div>
            <div class="col-md-4">
                <div class="blog_1r">
                    <div class="blog_1r1 p-4">
                        <h3 class="border-bottom">購物清單</h3>
                        <ul id="ticketitem">
                        </ul>
                        <ul id="productitem">
                        </ul>
                        <p id="calculate"></p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="next">
        <input type="submit" value="下一步" class="btn btn-primary" id="button" disabled />
    </div>
</form>
@section Scripts{
    <script type="text/javascript" src="~/js/Booking.js"></script>
    <script>
        function record(event) {
            var name = $(event).attr('name');
            var price = $(event).attr('price');
            var num = $(event).val();
            var id = $(event).attr('pid');

            $('#' + name).remove();
            $.ajax({
                method: 'POST',
                url: '/Shopping/ProductItem',
                data: {
                    productId: id,
                    quantity: num
                },
                success: function (data) {
                    if (data == 'pass') {
                        $("#productitem").append(`<li id="${name}">${name} <p>x${num} = ${num * price}</p></li>`);
                    } else {
                        console.log(data)
                    }

                },
                error: function (error) {
                    console.log(error);
                }
            });
        }
    </script>
}

ISpan.InseparableCore/Views/Shopping/CartView.cshtml
@model ISpan.InseparableCore.ViewModels.CcartviewVM

@{
    ViewData["Title"] = "CartView";
}
@section Styles{
    <link href="~/css/CartView.css" rel="stylesheet" />
}
    <h1>確認訂單</h1>
@using (Html.BeginForm("CreditPay", "Shopping", FormMethod.Post, new { id = "form" }))
{
    <div>
        <input type="hidden" name="FSessionId" value="@Model.session.FSessionId">
        <input type="hidden" name="FCinemaId" value="@Model.session.FCinemaId" />
        @foreach (var item in Model.movies)
        {

            <h1>@item.FMovieName</h1>
        }
        <h4><img src="https://img.icons8.com/ultraviolet/40/null/overtime.png" /> @Model.session.FSessionDate.ToString("yyyy/MM/dd") @Model.session.FSessionTime.Hours : @Model.session.FSessionTime.Minutes.ToString("D2")</h4>
        <h4>
            <img src="https://img.icons8.com/ios-filled/50/228BE6/aircraft-seat-middle.png" />
            @foreach (var item in Model.seats)
            {
                <span>@item.Value</span>
            }
        </h4>
    </div>
    <div>
        <table class="table table-dark table-striped table-hover">
            <thead>
                <tr>
                    <th>商品</th>
                    <th>價格</th>
                    <th>數量</th>
                    <th>合計</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.regular != 0)
                {
                    int regular = Model.regular;
                    int price = @Convert.ToInt32(Model.session.FTicketPrice);
                    int total = regular * price;
                    <input type="hidden" name="regular" value="@regular">
                    <tr>
                        <td id="regular">全票</td>
                        <td id="regularprice">@price</td>
                        <td>@regular</td>
                        <td id="regularsub">@total</td>
                    </tr>
                }
                @if (Model.concession != 0)
                {
                    int concession = Model.concession;
                    int price = (int)(@Convert.ToInt32(Model.session.FTicketPrice) * 0.9);
                    int total = concession * price;
                    <input type="hidden" name="concession" value="@concession">
                    <tr>
                        <td id="regular">優待票</td>
                        <td>@concession</td>
                        <td id="concessionprice">@price</td>
                        <td id="concessionsub">@total</td>
                    </tr>
                }
                @if (Model.cart != null)
                {

                    @foreach (var item in Model.cart)
                    {
                        var total = item.FProductUnitprice * item.FProductQty;
                        <tr>
                            <td>@item.FProductName</td>
                            <td>@item.FProductUnitprice.ToString("###")</td>
                            <td>@item.FProductQty.ToString("###")</td>
                            <td id="productsub">@total.ToString("###")</td>
                        </tr>
                    }
                }
                <tr class="border-top">
                    <td colspan="3">總額</td>
                    <td id="total"></td>
                </tr>
                <input type="hidden" name="FTotalMoney" id="money">
            </tbody>
        </table>
    </div>
    <div>
    </div>
    <div class="center">
        <input type="button" value="臨櫃付款" class="btn btn-primary" onclick="cashpay()" />
        <input type="submit" value="信用卡結帳" class="btn btn-primary" />
    </div>
}
@section Scripts{
    <script type="text/javascript" src="~/js/CartView.js"></script>
    <script>
        //window.history.pushState("", "", ""); //讓他到error
        window.history.pushState(null, null, '/Shopping/Order');
    </script>
}

ISpan.InseparableCore/Views/Shopping/CashPay.cshtml
@{
    ViewData["Title"] = "Paydone";
}
<form action="/Member/OrderHistory" method="get" id="form">
    <div style="text-align:center;" id="center">
        <br />
        <h2>訂購完成</h2>
        <br />
        <h4></h4>
    </div>
</form>
@section Scripts{
    <script>
        $(document).ready(function () {
            var count = 3;

            function updateCountdown() {
                if (count == 0) {
                    $('#center h4').text(`導回訂單紀錄`);
                }
                $('#center h4').text(`將於${count}秒後導回訂單記錄...`);
                count--;
            }

            updateCountdown();

            setInterval(updateCountdown, 1000);

            setTimeout(function () {
                $('#form').submit()
            }, 3000);
        });
    </script>
}

ISpan.InseparableCore/Views/Shopping/CreditPay.cshtml
@model Dictionary<string, string>
@{
    ViewData["Title"] = "Pay";
}

<link href="~/css/loading.css" rel="stylesheet" />
<div class="loadingdiv" id="loading" style="opacity: 1;">
    <img src="~/images/Infinity-1s-200px.gif" />
</div>
<form id="form" name="form" action="https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5" method="post" enctype="application/x-www-form-urlencoded">
    @foreach (var key in @Model.Keys.ToList())
    {
        @(key) <input type="text" name="@key" value="@Model[key]" />

        <br />
    }
</form>
<div id="order"></div>
<script>
    //var id = @ViewBag.order;
    window.onload = function () {
        document.getElementById("form").submit();
    }
    
    window.addEventListener("popstate", e => {
        window.location.href = `../Shopping/Order`;
    });
</script>

ISpan.InseparableCore/Views/Shopping/Pay.cshtml
@model Dictionary<string,string>
@{
    ViewData["Title"] = "Pay";
}

<link href="~/css/loading.css" rel="stylesheet" />
<div class="loadingdiv" id="loading" style="opacity: 1;">
    <img src="~/images/Infinity-1s-200px.gif" />
</div>
<form id="form" name="form" action="https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5" method="POST" enctype="application/x-www-form-urlencoded">
    @foreach (var key in @Model.Keys.ToList())
    {
        @(key) <input type="text" name="@key" value="@Model[key]" />

        <br />
    }
</form>
<script type="text/javascript">
    window.onload = function () {
        document.getElementById("form").submit();
    }
</script>

ISpan.InseparableCore/Views/Shopping/Paydone.cshtml
@{
    ViewData["Title"] = "Paydone";
}

<form action="/Member/OrderHistory" method="get" id="form">
    <div style="text-align:center;" id="center">
        <br />
        <h2>訂單: @ViewBag.No ,結帳完成</h2>
        <br />
        <h4></h4>
    </div>
</form>
@section Scripts{
    <script>
        $(document).ready(function () {
            var count = 3;

            function updateCountdown() {
                if (count == 0) {
                    $('#center h4').text(`導回訂單紀錄`);}
                $('#center h4').text(`將於${count}秒後導回訂單記錄...`);
                count--;
            }

            updateCountdown();

            setInterval(updateCountdown, 1000);

            setTimeout(function () {
                $('#form').submit()
            }, 3000);
        });
    </script>
}

ISpan.InseparableCore/Views/Shopping/Seat.cshtml
@model ISpan.InseparableCore.ViewModels.CseatVM

@{
    ViewData["Title"] = "Seat";
}


@section Styles{
    <link href="~/css//Seat.css" rel="stylesheet" />
}
    <form action="/Shopping/CartView" method="post" id="seat">
        @{
        <div class="title">
            @foreach (var item in Model.movie)
            {
                <h3>@item.FMovieName</h3>
            }
            <input type="hidden" name="sessionid" value="@Model.sessionid">
            <h4><img src="https://img.icons8.com/ultraviolet/40/null/overtime.png" /> @Model.sessions.FSessionDate.ToString("yyyy/MM/dd") @Model.sessions.FSessionTime.Hours : @Model.sessions.FSessionTime.Minutes.ToString("D2")</h4>
        </div>
        <div class="left">
            <span class="seleted"></span><p>您的座位</p>
            <span class="not-seleted"></span><p>可選座位</p>
            <span class="solid"></span><p>已售出</p>
            <p class="alert-danger" style="font-size:15px;" id="ticketnum"></p>
        </div>
        <div class="movie">
            <div class="screen"><p>螢幕</p></div>
            <div class="seat">
                <table>
                    @foreach (var item in Model.seats)
                    {
                        <tr>
                            <td>@item.Key</td>
                            @foreach (var column in item.Value)
                            {
                                <td>
                                    <div class="not-seleted" value="@column.FSeatId" id="@column.FSeatId">
                                        @column.FSeatColumn
                                    </div>
                                </td>

                                if (column.FSeatColumn == 2 || column.FSeatColumn == 12)
                                {
                                    <td><div class="aisle"></div></td>
                                }
                            }
                        </tr>
                    }
                </table>
            </div>
        </div>

    }
    <input type="hidden" name="regular" value="@Model.regularnum" />
    <input type="hidden" name="concession" value="@Model.concessionnum" />
    <div class="center" id="btnverif">
        <input type="submit" value="下一步" class="btn btn-primary" id="button" />
    </div>
</form>
@section Scripts{
    <script>
        var num = [];
        var ticket = @Model.ticket;

        onload = function () {
            var soldSeatIds = @Html.Raw(Json.Serialize(Model.solid));
            $(soldSeatIds).each(function (index, value) {
                $('#' + value).addClass('solid');
            });

            $('#ticketnum').html(`請選 ${ticket - num.length} 個座位!!!`);
            if (ticket == num.length) {
                $('#ticketnum').html(``);
            }

            //網頁重載 session清空
            $.ajax({
                method: 'POST',
                url: 'Clearticket',
                data: {},
                success: function (data) {
                },
                error: function (error) {
                }
            });

        }

        $("td div").click(function () {
            //忽略已賣出座位及走道
            if ($(this).hasClass('solid') | $(this).hasClass('aisle')) {
                return;
            }
            var sessionId = @Model.sessionid;
            //判斷選取座位及數量 紀錄座位
            if ($(this).hasClass('seleted')) {
                $(this).removeClass("seleted");
                $(this).addClass("not-seleted");
                var index = num.indexOf($(this).attr('value'));
                num.splice(index, 1);
                var seatId = $(this).attr('value');

                $.ajax({
                    method: 'POST',
                    url: '/Shopping/TicketItem',
                    data: {
                        seatId,
                        Qty: 0,
                        sessionId
                    },
                    success: function (data) {
                    },
                    error: function (error) {
                    }
                });
            }
            else {
                num.push($(this).attr('value'));
                if (num.length > ticket) {
                    num.pop();
                    Swal.fire("請先取消再選擇!!");
                    return;
                }
                $(this).removeClass("not-seleted");
                $(this).addClass("seleted");

                var seatId = $(this).attr('value');
                $.ajax({
                    method: 'POST',
                    url: '/Shopping/TicketItem',
                    data: {
                        seatId,
                        Qty: 1,
                        sessionId
                    },
                    success: function (data) {
                    },
                    error: function (error) {
                    }
                });
            }
            //小提醒
            $('#ticketnum').html(`請再選 ${ticket - num.length} 個座位 !!!`);
            if (ticket == num.length) {
                $('#ticketnum').html(``);
            }
        });

        $('#button').click(function (event) {
            //判斷選擇的位置數量是否正確
            var regular = @Model.regularnum;
            var concession = @Model.concessionnum;
            var session = @Model.sessionid;
            if (num.length != ticket) {
                event.preventDefault();
                Swal.fire(`還有 ${ticket - num.length} 個座位還沒選~~`);
            }
        });
    </script>
}